import phoneImg from "@/assets/gh-phone.jpg";
import laptopImg from "@/assets/gh-laptop.jpg";
import earbudsImg from "@/assets/gh-earbuds.jpg";
import watchImg from "@/assets/gh-watch.jpg";
import headphonesImg from "@/assets/gh-headphones.jpg";
import monitorImg from "@/assets/gh-monitor.jpg";
import keyboardImg from "@/assets/gh-keyboard.jpg";
import droneImg from "@/assets/gh-drone.jpg";
import speakerImg from "@/assets/gh-speaker.jpg";
import tabletImg from "@/assets/gh-tablet.jpg";
import powerbankImg from "@/assets/gh-powerbank.jpg";

export type Category = {
  slug: string;
  name: string;
  img: any;
  count: string;
  description: string;
  tagline: string;
  icon: string;
  popularBrands: string[];
};

export type Product = {
  slug: string;
  name: string;
  brand: string;
  category: string;
  price: number;
  was: number | null;
  img: any;
  rating: number;
  reviews: number;
  tag?: "New" | "Bestseller" | "Flash Deal" | "Pre-order" | "Official";
  warranty?: string;
  specs?: string[];
  inStock?: boolean;
  emiAvailable?: boolean;
};

export const CATEGORIES: Category[] = [
  {
    slug: "smartphones",
    name: "Smartphones",
    img: phoneImg,
    count: "128 models",
    description: "Flagships, foldables & performance monsters with 5G connectivity.",
    tagline: "Next-gen Flagships & 5G Devices",
    icon: "Smartphone",
    popularBrands: ["Apple", "Samsung", "Xiaomi", "Nothing"],
  },
  {
    slug: "laptops",
    name: "Laptops",
    img: laptopImg,
    count: "86 models",
    description: "Ultrabooks, creator workstations and elite high-refresh gaming rigs.",
    tagline: "Ultrabooks & High-Performance Rigs",
    icon: "Laptop",
    popularBrands: ["Apple", "ASUS", "Dell", "HP", "Lenovo"],
  },
  {
    slug: "earbuds",
    name: "Earbuds",
    img: earbudsImg,
    count: "54 models",
    description: "Active noise cancellation, spatial audio, and studio-grade wireless sound.",
    tagline: "True Wireless Sound & ANC Audio",
    icon: "Headphones",
    popularBrands: ["Apple", "Sony", "Samsung", "Nothing"],
  },
  {
    slug: "smartwatches",
    name: "Smart Watches",
    img: watchImg,
    count: "42 models",
    description: "AMOLED displays, ECG health monitoring, and multi-day battery endurance.",
    tagline: "Health Tracking & Premium Wearables",
    icon: "Watch",
    popularBrands: ["Apple", "Samsung", "Xiaomi"],
  },
  {
    slug: "headphones",
    name: "Headphones",
    img: headphonesImg,
    count: "38 models",
    description: "Hi-Res certified over-ear headphones with custom acoustic drivers.",
    tagline: "Audiophile Over-Ear Precision",
    icon: "Headphones",
    popularBrands: ["Sony", "Apple", "Logitech"],
  },
  {
    slug: "monitors",
    name: "Monitors",
    img: monitorImg,
    count: "31 models",
    description: "Ultra-wide 4K OLED, 240Hz esports panels, and calibrated color accuracy.",
    tagline: "OLED Gaming & Color-Accurate Displays",
    icon: "Monitor",
    popularBrands: ["Samsung", "ASUS", "Dell"],
  },
  {
    slug: "keyboards",
    name: "Keyboards",
    img: keyboardImg,
    count: "47 models",
    description: "Custom mechanical switches, hot-swappable PCBs, and aircraft-grade aluminum.",
    tagline: "Custom Mechanical & Wireless Peripherals",
    icon: "Keyboard",
    popularBrands: ["Logitech", "ASUS"],
  },
  {
    slug: "tablets",
    name: "Tablets",
    img: tabletImg,
    count: "28 models",
    description: "Pro-grade digital canvases with stylus latency and desktop multi-tasking.",
    tagline: "Pro Productivity & Creative Canvases",
    icon: "Tablet",
    popularBrands: ["Apple", "Samsung", "Xiaomi"],
  },
  {
    slug: "speakers",
    name: "Speakers",
    img: speakerImg,
    count: "22 models",
    description: "Room-filling 360° audio, deep bass radiators, and rugged waterproof designs.",
    tagline: "High-Fidelity Bluetooth & Home Audio",
    icon: "Volume2",
    popularBrands: ["Sony", "Xiaomi"],
  },
  {
    slug: "drones",
    name: "Drones",
    img: droneImg,
    count: "14 models",
    description: "Cinematic 4K/60fps aerial cinematography with obstacle avoidance.",
    tagline: "4K Aerial Cinematography & Gimbals",
    icon: "Plane",
    popularBrands: ["Xiaomi", "Sony"],
  },
  {
    slug: "power",
    name: "Power Banks",
    img: powerbankImg,
    count: "36 models",
    description: "100W+ Power Delivery high-speed charging for laptops and smartphones.",
    tagline: "Ultra-Fast GaN & High-Capacity PD",
    icon: "Zap",
    popularBrands: ["Xiaomi", "Nothing"],
  },
];

export const BRANDS = [
  "Apple",
  "Samsung",
  "ASUS",
  "Sony",
  "Xiaomi",
  "Nothing",
  "Dell",
  "HP",
  "Lenovo",
  "Logitech",
];

export const PRODUCTS: Product[] = [
  {
    slug: "galaxy-flagship-pro",
    name: "Galaxy Flagship Pro 5G 256GB (Snapdragon 8 Gen 3)",
    brand: "Samsung",
    category: "smartphones",
    price: 129900,
    was: 139900,
    img: phoneImg,
    rating: 4.9,
    reviews: 421,
    tag: "Bestseller",
    warranty: "1 Year Official",
    specs: ["200MP Camera", "6.8\" Dynamic AMOLED 2X", "5000mAh Battery", "S-Pen Included"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "aurora-ultrabook-14",
    name: "Aurora Ultrabook 14 OLED (Intel Core Ultra 7 / 16GB / 1TB)",
    brand: "ASUS",
    category: "laptops",
    price: 145900,
    was: 159900,
    img: laptopImg,
    rating: 4.8,
    reviews: 187,
    tag: "New",
    warranty: "2 Years Official",
    specs: ["14\" 2.8K 120Hz OLED", "Intel AI Boost NPU", "1.2kg Magnesium Body", "75Wh Battery"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "pods-pro-anc",
    name: "Pods Pro ANC 2nd Gen with USB-C MagSafe Case",
    brand: "Apple",
    category: "earbuds",
    price: 18990,
    was: 22990,
    img: earbudsImg,
    rating: 4.9,
    reviews: 812,
    tag: "Flash Deal",
    warranty: "1 Year Official",
    specs: ["2x Active Noise Cancelling", "Adaptive Audio", "30h Total Playtime", "IP54 Dust & Sweat"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "pulse-smartwatch-s3",
    name: "Pulse Smartwatch S3 Stainless Steel (1.43\" AMOLED)",
    brand: "Xiaomi",
    category: "smartwatches",
    price: 12500,
    was: 15900,
    img: watchImg,
    rating: 4.7,
    reviews: 356,
    tag: "Bestseller",
    warranty: "1 Year Official",
    specs: ["15-Day Battery Life", "Dual-Band GNSS GPS", "150+ Sports Modes", "5ATM Water Resistant"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "wave-anc-headphones",
    name: "Wave 1000XM Wireless Noise-Cancelling Headphones",
    brand: "Sony",
    category: "headphones",
    price: 34900,
    was: 38900,
    img: headphonesImg,
    rating: 4.8,
    reviews: 291,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["HD QN1 Noise Cancelling", "LDAC Hi-Res Audio", "30h Battery with Quick Charge", "Multipoint Connect"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "ultra-curved-34-oled",
    name: "Ultra Curved 34\" QD-OLED Gaming Monitor (175Hz 0.1ms)",
    brand: "Samsung",
    category: "monitors",
    price: 89900,
    was: 99900,
    img: monitorImg,
    rating: 4.9,
    reviews: 74,
    tag: "New",
    warranty: "3 Years",
    specs: ["3440x1440 UWQHD", "0.03ms Response Time", "Neo Quantum Processor", "Smart TV Apps Built-in"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "mech-rgb-keyboard-tkl",
    name: "Pro Mechanical RGB Wireless TKL Keyboard (Linear Red)",
    brand: "Logitech",
    category: "keyboards",
    price: 9990,
    was: 12990,
    img: keyboardImg,
    rating: 4.6,
    reviews: 512,
    tag: "Flash Deal",
    warranty: "2 Years",
    specs: ["LIGHTSPEED Wireless", "Low Profile GL Switches", "40h RGB Battery", "Aircraft Aluminum"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "sky-drone-4k",
    name: "Sky Drone 4K HDR Quadcopter Fly More Combo",
    brand: "Xiaomi",
    category: "drones",
    price: 62900,
    was: 69900,
    img: droneImg,
    rating: 4.7,
    reviews: 98,
    tag: "New",
    warranty: "1 Year",
    specs: ["4K/60fps HDR Video", "38 Min Flight Time", "10km Transmission", "Omnidirectional Sensing"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "boom-portable-speaker",
    name: "Boom XG-500 Rugged Waterproof Bluetooth Speaker",
    brand: "Sony",
    category: "speakers",
    price: 7990,
    was: 9990,
    img: speakerImg,
    rating: 4.6,
    reviews: 264,
    tag: "Flash Deal",
    warranty: "1 Year",
    specs: ["X-Balanced Speaker Unit", "30h Mega Battery", "IP66 Water & Dust Proof", "Ambient Party Lights"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "slate-tab-pro-11",
    name: "Slate Tab S9 Ultra 11\" AMOLED (128GB Wi-Fi + 5G)",
    brand: "Samsung",
    category: "tablets",
    price: 54900,
    was: 59900,
    img: tabletImg,
    rating: 4.8,
    reviews: 143,
    tag: "Bestseller",
    warranty: "1 Year Official",
    specs: ["120Hz Dynamic AMOLED", "Snapdragon 8 Gen 2", "IP68 S-Pen Included", "Quad AKG Speakers"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "watt-20k-power-bank",
    name: "HyperCharge 20000mAh 65W PD Laptop Power Bank",
    brand: "Xiaomi",
    category: "power",
    price: 3490,
    was: 4290,
    img: powerbankImg,
    rating: 4.7,
    reviews: 902,
    tag: "Bestseller",
    warranty: "6 Months",
    specs: ["65W Two-Way Fast Charge", "Triple Port Output", "Digital LED Display", "Airline Approved"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "neo-mini-phone",
    name: "Phone (2a) 5G Glyph Interface 128GB Special Edition",
    brand: "Nothing",
    category: "smartphones",
    price: 49900,
    was: 54900,
    img: phoneImg,
    rating: 4.7,
    reviews: 218,
    tag: "New",
    warranty: "1 Year Official",
    specs: ["Glyph Light Matrix", "Dimensity 7200 Pro", "50MP Dual Camera", "120Hz Flexible AMOLED"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "creator-laptop-16",
    name: "Creator XPS 16 Studio Edition (RTX 4070 / 32GB RAM)",
    brand: "Dell",
    category: "laptops",
    price: 239900,
    was: 259000,
    img: laptopImg,
    rating: 4.9,
    reviews: 62,
    tag: "Pre-order",
    warranty: "2 Years Official",
    specs: ["16.3\" 4K+ OLED Touch", "Intel Core Ultra 9", "NVIDIA RTX 4070 8GB", "CNC Aluminum Body"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "iphone-16-pro-max",
    name: "iPhone 16 Pro Max 256GB Natural Titanium (A18 Pro)",
    brand: "Apple",
    category: "smartphones",
    price: 184900,
    was: 195000,
    img: phoneImg,
    rating: 5.0,
    reviews: 630,
    tag: "Bestseller",
    warranty: "1 Year Official",
    specs: ["A18 Pro Bionic Chip", "Camera Control Button", "48MP Fusion Triple Camera", "Titanium Frame"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "rog-zephyrus-g16",
    name: "ROG Zephyrus G16 OLED Gaming Rig (RTX 4080 / 32GB)",
    brand: "ASUS",
    category: "laptops",
    price: 289900,
    was: 310000,
    img: laptopImg,
    rating: 4.9,
    reviews: 95,
    tag: "New",
    warranty: "2 Years Official",
    specs: ["16\" 2.5K 240Hz ROG Nebula OLED", "Intel Core Ultra 9 185H", "NVIDIA RTX 4080", "Slash Lighting Bar"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "apple-watch-ultra-2",
    name: "Apple Watch Ultra 2 GPS + Cellular 49mm Titanium",
    brand: "Apple",
    category: "smartwatches",
    price: 98900,
    was: 105000,
    img: watchImg,
    rating: 4.9,
    reviews: 180,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["3000 nits Brightness", "Precision Dual-Frequency GPS", "72h Low Power Battery", "100m Water Resistance"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "macbook-pro-14-m3",
    name: "MacBook Pro 14\" Space Black (M3 Pro / 18GB / 512GB)",
    brand: "Apple",
    category: "laptops",
    price: 245000,
    was: 260000,
    img: laptopImg,
    rating: 5.0,
    reviews: 310,
    tag: "Bestseller",
    warranty: "1 Year Official",
    specs: ["Liquid Retina XDR Display", "Apple M3 Pro Chip", "Up to 22h Battery Life", "Pro Connectivity Suite"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "ear-open-wireless",
    name: "Ear (a) Hi-Res Wireless Earbuds with Smart ANC",
    brand: "Nothing",
    category: "earbuds",
    price: 11900,
    was: 13900,
    img: earbudsImg,
    rating: 4.7,
    reviews: 142,
    tag: "Flash Deal",
    warranty: "1 Year Official",
    specs: ["45dB Smart ANC", "Custom 11mm Driver", "ChatGPT Integration", "42.5h Listening Time"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "ipad-pro-m4-13",
    name: "iPad Pro 13\" Ultra Retina XDR OLED (M4 Chip / 256GB)",
    brand: "Apple",
    category: "tablets",
    price: 169900,
    was: 179900,
    img: tabletImg,
    rating: 4.9,
    reviews: 114,
    tag: "New",
    warranty: "1 Year Official",
    specs: ["Tandem OLED Display", "Apple M4 Chip", "5.1mm Ultra Thin Design", "Apple Pencil Pro Support"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "logitech-mx-master-3s",
    name: "MX Master 3S Performance Wireless Ergonomic Mouse & Key Bundle",
    brand: "Logitech",
    category: "keyboards",
    price: 15490,
    was: 17900,
    img: keyboardImg,
    rating: 4.9,
    reviews: 480,
    tag: "Bestseller",
    warranty: "2 Years",
    specs: ["8K DPI Any-Surface Tracking", "Quiet Click Mechanism", "MagSpeed Electromagnetic Scroll", "Multi-OS Flow"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "anker-737-power-bank",
    name: "PowerCore 24000mAh 140W Multi-Device PD Power Bank",
    brand: "Nothing",
    category: "power",
    price: 14900,
    was: 16900,
    img: powerbankImg,
    rating: 4.8,
    reviews: 320,
    tag: "Flash Deal",
    warranty: "18 Months",
    specs: ["140W Ultra-Fast PD 3.1", "Smart Digital Display", "GaNPrime Tech", "Recharges in 52 Mins"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "alienware-32-4k-qd-oled",
    name: "Alienware 32\" 4K QD-OLED 240Hz Curved Gaming Display",
    brand: "Dell",
    category: "monitors",
    price: 159900,
    was: 175000,
    img: monitorImg,
    rating: 4.9,
    reviews: 45,
    tag: "Pre-order",
    warranty: "3 Years Official",
    specs: ["3840x2160 4K QD-OLED", "240Hz Refresh Rate", "Dolby Vision HDR", "0.03ms Gray-to-Gray"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "dji-mini-4-pro",
    name: "Aero Pro 4K HDR Ultralight Mini Drone (<249g)",
    brand: "Sony",
    category: "drones",
    price: 94900,
    was: 105000,
    img: droneImg,
    rating: 4.9,
    reviews: 86,
    tag: "Bestseller",
    warranty: "1 Year Official",
    specs: ["True Vertical 4K/60fps HDR", "Omnidirectional Obstacle Avoidance", "20km FHD Video Stream", "Sub-249g Regulation Free"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "jbl-boombox-3-wi-fi",
    name: "MegaBass 3 WiFi & Bluetooth 180W Portable Party Monster",
    brand: "Sony",
    category: "speakers",
    price: 46900,
    was: 52000,
    img: speakerImg,
    rating: 4.8,
    reviews: 168,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["180W RMS Massive Output", "Dolby Atmos 3D Sound", "24h Battery + Powerbank Output", "IP67 Dust & Water Proof"],
    inStock: true,
    emiAvailable: true,
  }
];

