import phoneImg from "@/assets/gh-phone.jpg";
import laptopImg from "@/assets/gh-laptop.jpg";
import earbudsImg from "@/assets/gh-earbuds.jpg";
import watchImg from "@/assets/gh-watch.jpg";
import headphonesImg from "@/assets/gh-headphones.jpg";
import monitorImg from "@/assets/gh-monitor.jpg";
import keyboardImg from "@/assets/gh-keyboard.jpg";
import droneImg from "@/assets/gh-drone.jpg";
import speakerImg from "@/assets/gh-speaker.jpg";
import tabletImg from "@/assets/gh-tablet.jpg";
import powerbankImg from "@/assets/gh-powerbank.jpg";

export type Category = {
  slug: string;
  name: string;
  img: any;
  count: string;
  description: string;
  tagline: string;
  icon: string;
  popularBrands: string[];
};

export type Product = {
  slug: string;
  name: string;
  brand: string;
  category: string;
  price: number;
  was: number | null;
  img: any;
  rating: number;
  reviews: number;
  tag?: "New" | "Bestseller" | "Flash Deal" | "Pre-order" | "Official";
  warranty?: string;
  specs?: string[];
  inStock?: boolean;
  emiAvailable?: boolean;
};

export const CATEGORIES: Category[] = [
  {
    slug: "smartphones",
    name: "Smartphones",
    img: phoneImg,
    count: "12 models",
    description: "Flagships, foldables & performance monsters with 5G connectivity.",
    tagline: "Next-gen Flagships & 5G Devices",
    icon: "Smartphone",
    popularBrands: ["Apple", "Samsung", "Xiaomi", "Nothing", "OnePlus", "Google"],
  },
  {
    slug: "laptops",
    name: "Laptops",
    img: laptopImg,
    count: "12 models",
    description: "Ultrabooks, creator workstations and elite high-refresh gaming rigs.",
    tagline: "Ultrabooks & High-Performance Rigs",
    icon: "Laptop",
    popularBrands: ["Apple", "ASUS", "Dell", "HP", "Lenovo", "Acer"],
  },
  {
    slug: "earbuds",
    name: "Earbuds",
    img: earbudsImg,
    count: "12 models",
    description: "Active noise cancellation, spatial audio, and studio-grade wireless sound.",
    tagline: "True Wireless Sound & ANC Audio",
    icon: "Headphones",
    popularBrands: ["Apple", "Sony", "Samsung", "Nothing", "Anker", "JBL"],
  },
  {
    slug: "smartwatches",
    name: "Smart Watches",
    img: watchImg,
    count: "12 models",
    description: "AMOLED displays, ECG health monitoring, and multi-day battery endurance.",
    tagline: "Health Tracking & Premium Wearables",
    icon: "Watch",
    popularBrands: ["Apple", "Samsung", "Xiaomi", "Amazfit", "Huawei", "CMF"],
  },
  {
    slug: "headphones",
    name: "Headphones",
    img: headphonesImg,
    count: "12 models",
    description: "Hi-Res certified over-ear headphones with custom acoustic drivers.",
    tagline: "Audiophile Over-Ear Precision",
    icon: "Headphones",
    popularBrands: ["Sony", "Bose", "Apple", "Sennheiser", "Logitech", "Razer"],
  },
  {
    slug: "monitors",
    name: "Monitors",
    img: monitorImg,
    count: "12 models",
    description: "Ultra-wide 4K OLED, 240Hz esports panels, and calibrated color accuracy.",
    tagline: "OLED Gaming & Color-Accurate Displays",
    icon: "Monitor",
    popularBrands: ["Samsung", "ASUS", "Dell", "LG", "Gigabyte", "BenQ"],
  },
  {
    slug: "keyboards",
    name: "Keyboards",
    img: keyboardImg,
    count: "12 models",
    description: "Custom mechanical switches, hot-swappable PCBs, and aircraft-grade aluminum.",
    tagline: "Custom Mechanical & Wireless Peripherals",
    icon: "Keyboard",
    popularBrands: ["Logitech", "Keychron", "Razer", "Corsair", "ASUS", "Royal Kludge"],
  },
  {
    slug: "tablets",
    name: "Tablets",
    img: tabletImg,
    count: "12 models",
    description: "Pro-grade digital canvases with stylus latency and desktop multi-tasking.",
    tagline: "Pro Productivity & Creative Canvases",
    icon: "Tablet",
    popularBrands: ["Apple", "Samsung", "Xiaomi", "OnePlus", "Lenovo"],
  },
  {
    slug: "speakers",
    name: "Speakers",
    img: speakerImg,
    count: "12 models",
    description: "Room-filling 360° audio, deep bass radiators, and rugged waterproof designs.",
    tagline: "High-Fidelity Bluetooth & Home Audio",
    icon: "Volume2",
    popularBrands: ["JBL", "Sony", "Marshall", "Harman Kardon", "Bose", "Anker"],
  },
  {
    slug: "drones",
    name: "Drones",
    img: droneImg,
    count: "12 models",
    description: "Cinematic 4K/60fps aerial cinematography with obstacle avoidance.",
    tagline: "4K Aerial Cinematography & Gimbals",
    icon: "Plane",
    popularBrands: ["DJI", "Xiaomi", "Sony", "Autel", "SJRC"],
  },
  {
    slug: "power",
    name: "Power Banks",
    img: powerbankImg,
    count: "12 models",
    description: "140W+ Power Delivery high-speed charging for laptops and smartphones.",
    tagline: "Ultra-Fast GaN & High-Capacity PD",
    icon: "Zap",
    popularBrands: ["Anker", "Baseus", "Xiaomi", "Ugreen", "Nothing", "Remax"],
  },
  {
    slug: "accessories",
    name: "Accessories",
    img: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80",
    count: "13 models",
    description: "Fast GaN chargers, braided cables, MagSafe cases, USB-C hubs & glass guards.",
    tagline: "Essential Cables, GaN Hubs & Cases",
    icon: "Tag",
    popularBrands: ["Apple", "Anker", "Baseus", "Ugreen", "Spigen", "ESR"],
  },
];

export const BRANDS = [
  "Apple",
  "Samsung",
  "ASUS",
  "Sony",
  "Xiaomi",
  "Nothing",
  "Dell",
  "HP",
  "Lenovo",
  "Logitech",
  "Anker",
  "Baseus",
  "Ugreen",
  "JBL",
  "OnePlus",
  "Google",
  "DJI",
  "Razer",
  "Keychron",
  "Spigen",
];

export const PRODUCTS: Product[] = [
  /* ─────────────────────────── SMARTPHONES (12 ITEMS) ─────────────────────────── */
  {
    slug: "iphone-16-pro-max",
    name: "iPhone 16 Pro Max 256GB Natural Titanium (A18 Pro)",
    brand: "Apple",
    category: "smartphones",
    price: 184900,
    was: 195000,
    img: phoneImg,
    rating: 5.0,
    reviews: 630,
    tag: "Bestseller",
    warranty: "1 Year Official",
    specs: ["A18 Pro Bionic Chip", "Camera Control Button", "48MP Fusion Triple Camera", "Grade 5 Titanium Frame"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "galaxy-flagship-pro",
    name: "Galaxy Flagship Pro S24 Ultra 5G 256GB (Snapdragon 8 Gen 3)",
    brand: "Samsung",
    category: "smartphones",
    price: 129900,
    was: 139900,
    img: phoneImg,
    rating: 4.9,
    reviews: 421,
    tag: "Bestseller",
    warranty: "1 Year Official",
    specs: ["200MP Quad Tele Camera", "6.8\" Dynamic AMOLED 2X 120Hz", "Built-in S-Pen", "Galaxy AI Enabled"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "xiaomi-14-pro-5g",
    name: "Xiaomi 14 Pro 5G Leica Optics 256GB (Snapdragon 8 Gen 3)",
    brand: "Xiaomi",
    category: "smartphones",
    price: 79900,
    was: 89900,
    img: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 310,
    tag: "Flash Deal",
    warranty: "1 Year Official",
    specs: ["Leica Summilux Variable Aperture", "120W HyperCharge", "2K WQHD+ 120Hz LTPO", "IP68 Dust & Water"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "neo-mini-phone",
    name: "Phone (2a) 5G Glyph Interface 128GB Special Edition",
    brand: "Nothing",
    category: "smartphones",
    price: 36900,
    was: 39900,
    img: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviews: 218,
    tag: "New",
    warranty: "1 Year Official",
    specs: ["Glyph Light Matrix Interface", "MediaTek Dimensity 7200 Pro", "50MP OIS Dual Camera", "120Hz Flexible AMOLED"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "iphone-15-128gb",
    name: "iPhone 15 128GB Dynamic Island Pink / Black (A16 Bionic)",
    brand: "Apple",
    category: "smartphones",
    price: 98500,
    was: 105000,
    img: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 380,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["Dynamic Island Interface", "48MP Main Camera 2x Telephoto", "USB-C Connectivity", "All-Day Battery Life"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "galaxy-a55-5g",
    name: "Samsung Galaxy A55 5G 8GB/128GB Awesome Navy",
    brand: "Samsung",
    category: "smartphones",
    price: 48900,
    was: 52000,
    img: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviews: 195,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["Metal Frame & Gorilla Glass Victus+", "50MP OIS Triple Camera", "Exynos 1480 4nm Chipset", "5000mAh Battery"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "redmi-note-13-pro-plus",
    name: "Xiaomi Redmi Note 13 Pro+ 5G 12GB/256GB Curved AMOLED",
    brand: "Xiaomi",
    category: "smartphones",
    price: 38500,
    was: 42000,
    img: "https://images.unsplash.com/photo-1567581935884-3349723552ca?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 410,
    tag: "Bestseller",
    warranty: "1 Year Official",
    specs: ["200MP OIS Ultra-Clear Camera", "120W HyperCharge in 19 mins", "1.5K 120Hz Curved AMOLED", "IP68 Water Resistance"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "google-pixel-8-pro",
    name: "Google Pixel 8 Pro 5G 128GB Bay Blue (Google Tensor G3)",
    brand: "Google",
    category: "smartphones",
    price: 92000,
    was: 98000,
    img: "https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 165,
    tag: "New",
    warranty: "1 Year Official",
    specs: ["Google AI & Best Take Camera", "Super Actua Display 2400 nits", "Pro Camera Controls with 5x Zoom", "7 Years OS Updates"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "oneplus-12-5g",
    name: "OnePlus 12 5G Hasselblad 16GB/512GB Silky Black",
    brand: "OnePlus",
    category: "smartphones",
    price: 84900,
    was: 89900,
    img: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 240,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["Snapdragon 8 Gen 3 Processor", "4th Gen Hasselblad Camera", "100W SUPERVOOC + 50W Wireless", "2K 120Hz ProXDR Display"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "galaxy-s24-fe",
    name: "Samsung Galaxy S24 FE 5G 8GB/256GB Mint",
    brand: "Samsung",
    category: "smartphones",
    price: 74500,
    was: 79900,
    img: "https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 140,
    tag: "New",
    warranty: "1 Year Official",
    specs: ["Exynos 2400e Flagship Silicon", "Galaxy AI Suite Enabled", "6.7\" Dynamic AMOLED 120Hz", "ProVisual Engine Cameras"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "realme-12-pro-plus",
    name: "Realme 12 Pro+ 5G Submarine Blue (64MP Periscope)",
    brand: "Realme",
    category: "smartphones",
    price: 38900,
    was: 42500,
    img: "https://images.unsplash.com/photo-1533228876829-65c94e7b5025?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviews: 180,
    tag: "Bestseller",
    warranty: "1 Year Official",
    specs: ["64MP Periscope Portrait Camera", "Luxury Watch Design by Ollivier Saveo", "120Hz Curved Vision Display", "Snapdragon 7s Gen 2"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "xiaomi-redmi-13c",
    name: "Xiaomi Redmi 13C 6GB/128GB Clover Green (Budget Value)",
    brand: "Xiaomi",
    category: "smartphones",
    price: 14500,
    was: 16500,
    img: "https://images.unsplash.com/photo-1585060544812-6b45742d762f?auto=format&fit=crop&w=800&q=80",
    rating: 4.6,
    reviews: 520,
    tag: "Bestseller",
    warranty: "1 Year Official",
    specs: ["6.74\" 90Hz Smooth Display", "50MP AI Triple Camera", "5000mAh Massive Battery", "MediaTek Helio G85"],
    inStock: true,
    emiAvailable: false,
  },

  /* ─────────────────────────── LAPTOPS (12 ITEMS) ─────────────────────────── */
  {
    slug: "aurora-ultrabook-14",
    name: "Aurora Ultrabook 14 OLED (Intel Core Ultra 7 / 16GB / 1TB)",
    brand: "ASUS",
    category: "laptops",
    price: 145900,
    was: 159900,
    img: laptopImg,
    rating: 4.8,
    reviews: 187,
    tag: "New",
    warranty: "2 Years Official",
    specs: ["14\" 2.8K 120Hz OLED Display", "Intel AI Boost NPU", "1.2kg Magnesium Body", "75Wh All-Day Battery"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "rog-zephyrus-g16",
    name: "ROG Zephyrus G16 OLED Gaming Rig (RTX 4080 / 32GB / Core Ultra 9)",
    brand: "ASUS",
    category: "laptops",
    price: 289900,
    was: 310000,
    img: laptopImg,
    rating: 4.9,
    reviews: 95,
    tag: "New",
    warranty: "2 Years Official",
    specs: ["16\" 2.5K 240Hz ROG Nebula OLED", "Intel Core Ultra 9 185H", "NVIDIA GeForce RTX 4080", "CNC Aluminum Body"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "macbook-pro-14-m3",
    name: "MacBook Pro 14\" Space Black (M3 Pro / 18GB / 512GB SSD)",
    brand: "Apple",
    category: "laptops",
    price: 245000,
    was: 260000,
    img: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80",
    rating: 5.0,
    reviews: 310,
    tag: "Bestseller",
    warranty: "1 Year Official",
    specs: ["Liquid Retina XDR Display", "Apple M3 Pro Chip", "Up to 22h Battery Endurance", "Pro Connectivity Ports"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "macbook-air-13-m2",
    name: "MacBook Air 13.6\" Midnight (Apple M2 / 8GB / 256GB SSD)",
    brand: "Apple",
    category: "laptops",
    price: 118500,
    was: 125000,
    img: "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 580,
    tag: "Bestseller",
    warranty: "1 Year Official",
    specs: ["Apple M2 8-core CPU / 8-core GPU", "13.6\" Liquid Retina Display", "MagSafe 3 Fast Charging", "1.24kg Ultra-Thin Profile"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "creator-laptop-16",
    name: "Creator XPS 16 Studio Edition (RTX 4070 / 32GB RAM / 1TB SSD)",
    brand: "Dell",
    category: "laptops",
    price: 239900,
    was: 259000,
    img: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 62,
    tag: "Pre-order",
    warranty: "2 Years Official",
    specs: ["16.3\" 4K+ OLED Touch Panel", "Intel Core Ultra 9 185H", "NVIDIA RTX 4070 8GB", "CNC Machined Aluminum"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "lenovo-legion-pro-5i",
    name: "Lenovo Legion Pro 5i Gen 9 (Core i7-14700HX / RTX 4070 / 16GB)",
    brand: "Lenovo",
    category: "laptops",
    price: 178000,
    was: 189000,
    img: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 112,
    tag: "Official",
    warranty: "2 Years Official",
    specs: ["16\" WQXGA 240Hz PureSight Gaming", "RTX 4070 8GB GDDR6 (140W TGP)", "Lenovo AI Engine+ (LA1 Chip)", "ColdFront 5.0 Thermal Tech"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "asus-tuf-gaming-f15",
    name: "ASUS TUF Gaming F15 (Core i7-13620H / RTX 4060 / 16GB / 512GB)",
    brand: "ASUS",
    category: "laptops",
    price: 98500,
    was: 106000,
    img: "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviews: 290,
    tag: "Bestseller",
    warranty: "2 Years Official",
    specs: ["15.6\" FHD 144Hz IPS Display", "NVIDIA RTX 4060 8GB GDDR6", "Military-Grade Toughness MIL-STD", "90Wh Fast-Charging Battery"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "hp-spectre-x360-14",
    name: "HP Spectre x360 14 2-in-1 OLED (Intel Core Ultra 7 / 32GB / 1TB)",
    brand: "HP",
    category: "laptops",
    price: 185000,
    was: 198000,
    img: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 75,
    tag: "New",
    warranty: "2 Years Official",
    specs: ["14\" 2.8K 120Hz IMAX OLED Touch", "HP Rechargeable MPP2.0 Tilt Pen", "Poly Studio Audio 4 Speakers", "9MP AI Smart Webcam"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "dell-inspiron-15-3520",
    name: "Dell Inspiron 15 3520 (Intel Core i5-1235U / 8GB / 512GB SSD)",
    brand: "Dell",
    category: "laptops",
    price: 58500,
    was: 63000,
    img: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=800&q=80",
    rating: 4.6,
    reviews: 340,
    tag: "Official",
    warranty: "2 Years Official",
    specs: ["15.6\" FHD 120Hz Anti-Glare Display", "Intel Core i5 10-core Processor", "Dell ComfortView Blue Light Tech", "ExpressCharge 80% in 60 mins"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "lenovo-ideapad-slim-3",
    name: "Lenovo IdeaPad Slim 3 15IRH8 (Core i5-13420H / 16GB / 512GB SSD)",
    brand: "Lenovo",
    category: "laptops",
    price: 64500,
    was: 69000,
    img: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviews: 215,
    tag: "Bestseller",
    warranty: "2 Years Official",
    specs: ["15.6\" FHD IPS 300 nits Display", "High-Performance 45W H-Series CPU", "User-Facing Dolby Audio", "Rapid Charge Boost (2hr in 15min)"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "hp-pavilion-15-eg3000",
    name: "HP Pavilion 15 (Core i5-1335U / 16GB RAM / 512GB SSD / Iris Xe)",
    brand: "HP",
    category: "laptops",
    price: 72900,
    was: 78000,
    img: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviews: 180,
    tag: "Official",
    warranty: "2 Years Official",
    specs: ["15.6\" Micro-Edge Full HD IPS", "Audio by B&O Dual Speakers", "Backlit Keyboard with Numeric Keypad", "Precision Aluminum Top Cover"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "acer-predator-helios-neo-16",
    name: "Acer Predator Helios Neo 16 (Core i7-14650HX / RTX 4060 / 16GB)",
    brand: "ASUS",
    category: "laptops",
    price: 152000,
    was: 162000,
    img: "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 88,
    tag: "New",
    warranty: "2 Years Official",
    specs: ["16\" WQXGA 165Hz sRGB 100% Display", "5th Gen AeroBlade 3D Fan Cooling", "RGB 4-Zone Backlit Gaming Keyboard", "Killer Ethernet E3100G + Wi-Fi 6E"],
    inStock: true,
    emiAvailable: true,
  },

  /* ─────────────────────────── EARBUDS (12 ITEMS) ─────────────────────────── */
  {
    slug: "pods-pro-anc",
    name: "Pods Pro ANC 2nd Gen with USB-C MagSafe Case",
    brand: "Apple",
    category: "earbuds",
    price: 18990,
    was: 22990,
    img: earbudsImg,
    rating: 4.9,
    reviews: 812,
    tag: "Flash Deal",
    warranty: "1 Year Official",
    specs: ["2x Active Noise Cancelling", "Adaptive Audio & Transparency", "30h Total Playtime with Case", "IP54 Dust & Sweat Resistant"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "ear-open-wireless",
    name: "Ear (a) Hi-Res Wireless Earbuds with Smart ANC",
    brand: "Nothing",
    category: "earbuds",
    price: 11900,
    was: 13900,
    img: earbudsImg,
    rating: 4.7,
    reviews: 142,
    tag: "Flash Deal",
    warranty: "1 Year Official",
    specs: ["45dB Smart Active Noise Cancellation", "Custom 11mm Dynamic Driver", "ChatGPT Integration Enabled", "42.5h Total Listening Endurance"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "sony-wf-1000xm5",
    name: "Sony WF-1000XM5 Industry Leading Noise Cancelling Earbuds",
    brand: "Sony",
    category: "earbuds",
    price: 26500,
    was: 29500,
    img: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 320,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["Dual Feedback Microphones & V2 Processor", "Dynamic Driver X Audio Reproduction", "Bone Conduction Sensor Mic", "Wireless Charging Case with IPX4"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "galaxy-buds3-pro",
    name: "Samsung Galaxy Buds3 Pro Blade Lights & Hi-Fi 24-bit Audio",
    brand: "Samsung",
    category: "earbuds",
    price: 21500,
    was: 23900,
    img: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 210,
    tag: "New",
    warranty: "1 Year Official",
    specs: ["Iconic Blade Light Design", "2-Way Speaker with Planar Tweeter", "Galaxy AI Real-Time Interpreter", "Adaptive Noise Control"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "anker-soundcore-liberty-4-nc",
    name: "Anker Soundcore Liberty 4 NC 98.5% Noise Reduction Earbuds",
    brand: "Anker",
    category: "earbuds",
    price: 8900,
    was: 10500,
    img: "https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 450,
    tag: "Bestseller",
    warranty: "18 Months Official",
    specs: ["Adaptive ANC 2.0 Real-Time Adjust", "11mm Custom Drivers with LDAC", "50h Long Playtime with Wireless Case", "6 Mics AI Clear Calls"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "apple-airpods-3",
    name: "Apple AirPods 3rd Generation with Lightning / MagSafe Case",
    brand: "Apple",
    category: "earbuds",
    price: 16500,
    was: 18500,
    img: "https://images.unsplash.com/photo-1588423771073-b8903fbb85b5?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 520,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["Personalized Spatial Audio with Head Tracking", "Adaptive EQ Music Calibration", "IPX4 Sweat and Water Resistance", "Up to 30 Hours Total Listening"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "nothing-ear-2",
    name: "Nothing Ear (2) Hi-Res Dual Chamber Sound Transparent Edition",
    brand: "Nothing",
    category: "earbuds",
    price: 13500,
    was: 15500,
    img: "https://images.unsplash.com/photo-1629367494173-c78a56567877?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviews: 190,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["LHDC 5.0 Certified Hi-Res Audio", "Personalized Sound Profiles via App", "Dual Connection Multipoint", "36 Hours Total Listening Time"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "oneplus-buds-pro-2",
    name: "OnePlus Buds Pro 2 Dynaudio Co-Created Spatial Audio",
    brand: "OnePlus",
    category: "earbuds",
    price: 12500,
    was: 14500,
    img: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 230,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["MelodyBoost Dual Drivers by Dynaudio", "48dB Smart Adaptive Noise Cancelling", "Google Fast Pair & Dual Connection", "Up to 39h Total Playback"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "realme-buds-air-5-pro",
    name: "Realme Buds Air 5 Pro 50dB Active Noise Cancellation",
    brand: "Realme",
    category: "earbuds",
    price: 6900,
    was: 7900,
    img: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviews: 310,
    tag: "Bestseller",
    warranty: "1 Year Official",
    specs: ["Dual Coaxial Drivers (11mm + 6mm)", "50dB Deep Sea Noise Reduction 2.0", "LDAC Hi-Res Audio Transmission", "40h Max Battery Endurance"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "jbl-live-pro-2",
    name: "JBL Live Pro 2 True Adaptive Noise Cancelling Earbuds",
    brand: "JBL",
    category: "earbuds",
    price: 14500,
    was: 16500,
    img: "https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviews: 140,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["JBL Signature Deep Bass Sound", "True Adaptive ANC with Smart Ambient", "6 Microphones for Perfect Calls", "Qi-Compatible Wireless Charging"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "baseus-bowie-m2-plus",
    name: "Baseus Bowie M2+ Hybrid 42dB ANC Earbuds (Budget King)",
    brand: "Baseus",
    category: "earbuds",
    price: 3450,
    was: 3990,
    img: "https://images.unsplash.com/photo-1629367494173-c78a56567877?auto=format&fit=crop&w=800&q=80",
    rating: 4.6,
    reviews: 480,
    tag: "Bestseller",
    warranty: "6 Months Official",
    specs: ["Hybrid 42dB Noise Cancellation", "Baseus Rapid Charge (10m for 2h)", "Bluetooth 5.2 Low Latency 0.038s", "Baseus Smart App Custom EQ"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "xiaomi-redmi-buds-5-pro",
    name: "Xiaomi Redmi Buds 5 Pro 52dB ANC Hi-Res Coaxial Earbuds",
    brand: "Xiaomi",
    category: "earbuds",
    price: 5200,
    was: 5900,
    img: "https://images.unsplash.com/photo-1588423771073-b8903fbb85b5?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 320,
    tag: "Official",
    warranty: "6 Months Official",
    specs: ["Custom Coaxial Dual Drivers (Titanium + Ceramic)", "52dB 4kHz Ultra-Wideband ANC", "Built-In Immersive Sound Modes", "38 Hours Long Playtime"],
    inStock: true,
    emiAvailable: false,
  },

  /* ─────────────────────────── SMARTWATCHES (12 ITEMS) ─────────────────────────── */
  {
    slug: "apple-watch-ultra-2",
    name: "Apple Watch Ultra 2 GPS + Cellular 49mm Titanium",
    brand: "Apple",
    category: "smartwatches",
    price: 98900,
    was: 105000,
    img: watchImg,
    rating: 4.9,
    reviews: 180,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["3000 nits Retina Display", "Precision Dual-Frequency GPS", "72h Low Power Battery", "100m Water Resistance"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "galaxy-watch-ultra-lte",
    name: "Galaxy Watch Ultra 47mm LTE Titanium (100m Water / AI Health)",
    brand: "Samsung",
    category: "smartwatches",
    price: 49900,
    was: 58900,
    img: watchImg,
    rating: 4.8,
    reviews: 245,
    tag: "Flash Deal",
    warranty: "1 Year Official",
    specs: ["Cushion Titanium Design", "Dual-Frequency GPS", "3000 nits AMOLED", "100h Battery Endurance"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "pulse-smartwatch-s3",
    name: "Pulse Smartwatch S3 Stainless Steel (1.43\" AMOLED 60Hz)",
    brand: "Xiaomi",
    category: "smartwatches",
    price: 12500,
    was: 15900,
    img: watchImg,
    rating: 4.7,
    reviews: 356,
    tag: "Bestseller",
    warranty: "1 Year Official",
    specs: ["15-Day Battery Life", "Dual-Band GNSS GPS", "150+ Sports Modes", "5ATM Water Resistant"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "apple-watch-series-9",
    name: "Apple Watch Series 9 GPS 45mm Midnight Aluminum (S9 SiP)",
    brand: "Apple",
    category: "smartwatches",
    price: 49500,
    was: 54000,
    img: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 290,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["Double Tap Gesture Control", "2000 nits Always-On Retina", "ECG App & Blood Oxygen Sensor", "Crash Detection & Fall Detection"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "samsung-galaxy-watch-6-classic",
    name: "Samsung Galaxy Watch 6 Classic 47mm Rotating Bezel BT",
    brand: "Samsung",
    category: "smartwatches",
    price: 29500,
    was: 33000,
    img: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 175,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["Physical Rotating Bezel Control", "Sapphire Crystal Super AMOLED", "Personalized Heart Rate Zones", "BIA Body Composition Analysis"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "amazfit-gtr-4",
    name: "Amazfit GTR 4 AMOLED Display Dual-Band GPS Bluetooth Calls",
    brand: "Xiaomi",
    category: "smartwatches",
    price: 18900,
    was: 21500,
    img: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 210,
    tag: "Bestseller",
    warranty: "1 Year Official",
    specs: ["14-Day Ultra-Long Battery Life", "Industry-First Dual-Band Circularly-Polarized GPS", "150+ Sports Modes & Strength Recognition", "Zepp OS 2.0 Ecosystem"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "huawei-watch-gt-4",
    name: "Huawei Watch GT 4 46mm Stainless Steel Geometric Design",
    brand: "Xiaomi",
    category: "smartwatches",
    price: 23500,
    was: 26000,
    img: "https://images.unsplash.com/photo-1544117519-31a4b719223d?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 130,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["Up to 14 Days Battery Endurance", "TruSeen 5.5+ Enhanced Heart Rate", "Science-Based Calorie Management", "Compatible with iOS & Android"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "cmf-watch-pro-2",
    name: "CMF Watch Pro 2 by Nothing Interchangeable Bezel 1.32\" AMOLED",
    brand: "Nothing",
    category: "smartwatches",
    price: 7500,
    was: 8500,
    img: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviews: 310,
    tag: "New",
    warranty: "1 Year Official",
    specs: ["Interchangeable Bezel Craftsmanship", "1.32\" AMOLED with Auto-Brightness", "Bluetooth Calls with AI Noise Reduction", "Multi-System Built-In GPS"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "xiaomi-watch-2-pro",
    name: "Xiaomi Watch 2 Pro WearOS Snapdragon W5+ Gen 1 AMOLED",
    brand: "Xiaomi",
    category: "smartwatches",
    price: 22500,
    was: 25000,
    img: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviews: 95,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["Google WearOS with Play Store & Maps", "Snapdragon W5+ Gen 1 4nm Processor", "Rotating Crown & Classic Stainless Steel", "5-System Dual-Band L1+L5 GNSS"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "kieslect-kr-pro",
    name: "Kieslect Kr Pro Calling Smartwatch 1.43\" Ultra FHD AMOLED",
    brand: "Xiaomi",
    category: "smartwatches",
    price: 6200,
    was: 6990,
    img: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80",
    rating: 4.6,
    reviews: 410,
    tag: "Bestseller",
    warranty: "1 Year Official",
    specs: ["Stable Bluetooth 5.2 Phone Calls", "1.43\" Ultra FHD AMOLED Display", "Vibrant Quick-Release Magnetic Strap", "70 Sports Modes & Health Monitors"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "haylou-solar-plus-rt3",
    name: "Haylou Solar Plus RT3 AMOLED Bluetooth Phone Call Smartwatch",
    brand: "Xiaomi",
    category: "smartwatches",
    price: 3850,
    was: 4500,
    img: "https://images.unsplash.com/photo-1544117519-31a4b719223d?auto=format&fit=crop&w=800&q=80",
    rating: 4.6,
    reviews: 540,
    tag: "Bestseller",
    warranty: "6 Months Official",
    specs: ["1.43\" 466x466 AMOLED Screen", "Bluetooth 5.3 One-Tap Phone Calling", "IP68 Professional Waterproof", "SpO2 & All-Day Heart Rate Tracking"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "mibro-lite-2",
    name: "Mibro Lite 2 HD AMOLED Dual-Strap Bluetooth Calling Smartwatch",
    brand: "Xiaomi",
    category: "smartwatches",
    price: 4600,
    was: 5200,
    img: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80",
    rating: 4.6,
    reviews: 320,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["Metal Body with Leather + Silicone Straps", "HD AMOLED Display Always-On Mode", "24H Heart Rate & SpO2 Measurement", "2ATM Water Resistance Rating"],
    inStock: true,
    emiAvailable: false,
  },

  /* ─────────────────────────── HEADPHONES (12 ITEMS) ─────────────────────────── */
  {
    slug: "wave-anc-headphones",
    name: "Wave 1000XM Wireless Noise-Cancelling Headphones (WH-1000XM5)",
    brand: "Sony",
    category: "headphones",
    price: 34900,
    was: 38900,
    img: headphonesImg,
    rating: 4.8,
    reviews: 291,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["Auto NC Optimizer with 8 Microphones", "LDAC Studio Hi-Res Wireless Audio", "30h Battery Life with Quick Charge", "Speak-to-Chat & Multipoint Connection"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "zone-anc-gaming-headset",
    name: "Zone Pro Wireless ANC Spatial Audio Gaming Headset",
    brand: "Sony",
    category: "headphones",
    price: 15900,
    was: 19900,
    img: headphonesImg,
    rating: 4.7,
    reviews: 198,
    tag: "Flash Deal",
    warranty: "1 Year Official",
    specs: ["Dual ANC Microphones", "360 Spatial Sound for Gaming", "40h Battery with Quick Charge", "2.4GHz + BT Multipoint"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "apple-airpods-max",
    name: "Apple AirPods Max Space Gray Computational Spatial Audio",
    brand: "Apple",
    category: "headphones",
    price: 69900,
    was: 76000,
    img: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 145,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["Apple-Designed Dynamic Acoustic Driver", "Pro-Level Active Noise Cancellation", "Knit-Mesh Canopy & Memory Foam Cups", "Digital Crown for Volume & Siri"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "bose-quietcomfort-ultra",
    name: "Bose QuietComfort Ultra Headphones Immersive Spatial Audio",
    brand: "Bose",
    category: "headphones",
    price: 44500,
    was: 48900,
    img: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 120,
    tag: "New",
    warranty: "1 Year Official",
    specs: ["Breakthrough Bose Immersive Audio", "CustomTune Technology Calibration", "Ultra-Soft Cushions with Minimal Clamping", "24 Hours Battery Life"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "sennheiser-momentum-4",
    name: "Sennheiser Momentum 4 Wireless Audiophile ANC Headphones",
    brand: "Sony",
    category: "headphones",
    price: 36500,
    was: 39900,
    img: "https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 95,
    tag: "Official",
    warranty: "2 Years Official",
    specs: ["Incredible 60-Hour Battery Endurance", "42mm Transducer Sound Precision", "Adaptive Noise Cancellation & Transparency", "Lightweight Fold-Flat Travel Design"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "audio-technica-ath-m50xbt2",
    name: "Audio-Technica ATH-M50xBT2 Professional Studio Wireless",
    brand: "Sony",
    category: "headphones",
    price: 22500,
    was: 24900,
    img: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 210,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["Proprietary 45mm Large-Aperture Drivers", "AK4331 Advanced DAC and Internal Amp", "Low Latency Mode for Gaming & Video", "50 Hours Battery with Rapid Charge"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "anker-soundcore-space-q45",
    name: "Anker Soundcore Space Q45 Adaptive Active Noise Cancelling",
    brand: "Anker",
    category: "headphones",
    price: 12500,
    was: 14500,
    img: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 380,
    tag: "Bestseller",
    warranty: "18 Months Official",
    specs: ["98% Noise Reduction Adaptive System", "LDAC Wireless Hi-Res Audio Certified", "65-Hour Ultra-Long Playtime", "Ergonomic Ultra-Comfort Fit"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "razer-blackshark-v2-pro",
    name: "Razer BlackShark V2 Pro Wireless Esports Gaming Headset",
    brand: "Razer",
    category: "headphones",
    price: 18500,
    was: 21000,
    img: "https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 185,
    tag: "Official",
    warranty: "2 Years Official",
    specs: ["Razer HyperClear Super Wideband Mic", "TriForce Titanium 50mm Drivers", "Ultra-Soft Breathable Memory Foam", "70 Hours Battery Life with Type-C"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "logitech-g733-lightspeed",
    name: "Logitech G733 LIGHTSPEED Wireless RGB Gaming Headset",
    brand: "Logitech",
    category: "headphones",
    price: 14900,
    was: 16900,
    img: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviews: 260,
    tag: "Bestseller",
    warranty: "2 Years Official",
    specs: ["LIGHTSPEED 20m Range Wireless", "Front-Facing LIGHTSYNC Dual-Zone RGB", "PRO-G Audio Drivers with DTS Headphone:X", "Ultra-Lightweight 278g Suspension Strap"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "jbl-tour-one-m2",
    name: "JBL Tour One M2 True Adaptive Noise Cancelling Hi-Res",
    brand: "JBL",
    category: "headphones",
    price: 28000,
    was: 32000,
    img: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviews: 75,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["True Adaptive Noise Cancelling with 4 Mics", "JBL Spatial Sound Stage Performance", "Smart Talk Voice Recognition", "50 Hours Playtime with Speed Charge"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "anker-soundcore-life-q30",
    name: "Anker Soundcore Life Q30 Hybrid Active Noise Cancelling",
    brand: "Anker",
    category: "headphones",
    price: 7200,
    was: 8200,
    img: "https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviews: 620,
    tag: "Bestseller",
    warranty: "18 Months Official",
    specs: ["Multi-Mode Active Noise Cancellation", "Hi-Res Audio with 40mm Silk Drivers", "40-Hour Battery Life with ANC On", "NFC Fast Bluetooth Pairing"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "edifier-w820nb-plus",
    name: "Edifier W820NB Plus LDAC Hi-Res Audio -43dB ANC Headphone",
    brand: "Sony",
    category: "headphones",
    price: 4900,
    was: 5600,
    img: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80",
    rating: 4.6,
    reviews: 410,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["43dB Deep Hybrid Noise Cancellation", "LDAC High-Definition Audio Codec", "49 Hours Battery Playback", "0.08s Ultra-Low Latency Gaming"],
    inStock: true,
    emiAvailable: false,
  },

  /* ─────────────────────────── MONITORS (12 ITEMS) ─────────────────────────── */
  {
    slug: "ultra-curved-34-oled",
    name: "Ultra Curved 34\" QD-OLED Gaming Monitor (175Hz 0.1ms)",
    brand: "Samsung",
    category: "monitors",
    price: 89900,
    was: 99900,
    img: monitorImg,
    rating: 4.9,
    reviews: 74,
    tag: "New",
    warranty: "3 Years Official",
    specs: ["3440x1440 UWQHD Resolution", "0.03ms Response Time", "Neo Quantum Processor", "Built-In Smart TV Hub Apps"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "curved-gaming-monitor-27-240hz",
    name: "Odyssey G7 27\" WQHD 240Hz Curved Gaming Monitor (1000R)",
    brand: "Samsung",
    category: "monitors",
    price: 52900,
    was: 62000,
    img: monitorImg,
    rating: 4.9,
    reviews: 189,
    tag: "Flash Deal",
    warranty: "3 Years Official",
    specs: ["1000R Deep Human Field Curve", "WQHD 2560x1440 240Hz 1ms", "Quantum Dot HDR600 Vividness", "G-Sync & FreeSync Premium Pro"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "alienware-32-4k-qd-oled",
    name: "Alienware 32\" 4K QD-OLED 240Hz Curved Gaming Display",
    brand: "Dell",
    category: "monitors",
    price: 159900,
    was: 175000,
    img: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 45,
    tag: "Pre-order",
    warranty: "3 Years Official",
    specs: ["3840x2160 4K QD-OLED Panel", "240Hz Native Refresh Rate", "Dolby Vision & VESA DisplayHDR", "0.03ms Gray-to-Gray Response"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "samsung-odyssey-oled-g9",
    name: "Samsung Odyssey OLED G9 49\" Dual QHD 240Hz 0.03ms Curved",
    brand: "Samsung",
    category: "monitors",
    price: 165000,
    was: 185000,
    img: "https://images.unsplash.com/photo-1547119957-637f8679db1e?auto=format&fit=crop&w=800&q=80",
    rating: 5.0,
    reviews: 38,
    tag: "Official",
    warranty: "3 Years Official",
    specs: ["49\" 32:9 Super Ultra-Wide 5120x1440", "0.03ms GtG Response & 240Hz", "Neo Quantum Processor Pro", "CoreSync & Core Lighting+"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "dell-ultrasharp-u2723qe",
    name: "Dell UltraSharp U2723QE 27\" 4K UHD IPS Black USB-C Hub Monitor",
    brand: "Dell",
    category: "monitors",
    price: 68500,
    was: 74000,
    img: "https://images.unsplash.com/photo-1586775490184-b79f0621891f?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 95,
    tag: "Official",
    warranty: "3 Years Official",
    specs: ["27\" 4K UHD 3840x2160 IPS Black", "2000:1 Contrast Ratio (Deep Blacks)", "90W Power Delivery USB-C Hub", "98% DCI-P3 & VESA DisplayHDR 400"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "lg-ultragear-27-oled",
    name: "LG UltraGear 27GR95QE-B 27\" QHD OLED 240Hz 0.03ms Gaming",
    brand: "ASUS",
    category: "monitors",
    price: 94500,
    was: 104000,
    img: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 68,
    tag: "New",
    warranty: "3 Years Official",
    specs: ["27\" QHD 2560x1440 OLED Panel", "Blazing 240Hz Refresh & 0.03ms", "Anti-Glare Low Reflection Tech", "G-Sync Compatible & FreeSync Premium"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "asus-rog-swift-pg27aqdm",
    name: "ASUS ROG Swift PG27AQDM 27\" 1440p 240Hz OLED Gaming Monitor",
    brand: "ASUS",
    category: "monitors",
    price: 118000,
    was: 129000,
    img: "https://images.unsplash.com/photo-1547119957-637f8679db1e?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 52,
    tag: "Official",
    warranty: "3 Years Official",
    specs: ["Custom Heatsink for Anti-Burn-In Protection", "1000 nits Peak HDR Brightness", "99% DCI-P3 Color Gamut", "Uniform Brightness Setting"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "asus-tuf-vg27aq",
    name: "ASUS TUF Gaming VG27AQ 27\" WQHD 165Hz IPS G-Sync Gaming",
    brand: "ASUS",
    category: "monitors",
    price: 37500,
    was: 41000,
    img: "https://images.unsplash.com/photo-1586775490184-b79f0621891f?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 310,
    tag: "Bestseller",
    warranty: "3 Years Official",
    specs: ["27\" WQHD 2560x1440 Fast IPS", "ELMB Sync Motion Blur Reduction", "165Hz Refresh Rate & 1ms MPRT", "Ergonomic Height, Tilt & Swivel Stand"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "gigabyte-m27q",
    name: "Gigabyte M27Q 27\" 170Hz 1440p SS IPS Gaming Monitor with KVM",
    brand: "ASUS",
    category: "monitors",
    price: 35000,
    was: 38500,
    img: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviews: 240,
    tag: "Bestseller",
    warranty: "3 Years Official",
    specs: ["Built-In KVM Switch Button", "SuperSpeed IPS Panel 0.5ms MPRT", "92% DCI-P3 8-bit Color Depth", "VESA DisplayHDR 400 Certified"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "benq-mobiuz-ex2710q",
    name: "BenQ MOBIUZ EX2710Q 27\" QHD 165Hz IPS HDRi Gaming Monitor",
    brand: "Dell",
    category: "monitors",
    price: 42000,
    was: 46500,
    img: "https://images.unsplash.com/photo-1547119957-637f8679db1e?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 110,
    tag: "Official",
    warranty: "3 Years Official",
    specs: ["treVolo 2.1 Channel Sound (Subwoofer)", "HDRi Intelligent Optimization Sensor", "165Hz IPS with 1ms MPRT", "Scenario Mapping Auto Profiles"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "msi-optix-mag342cqr",
    name: "MSI Optix MAG342CQR 34\" UWQHD 144Hz 1500R Curved Gaming",
    brand: "ASUS",
    category: "monitors",
    price: 48500,
    was: 54000,
    img: "https://images.unsplash.com/photo-1586775490184-b79f0621891f?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviews: 135,
    tag: "Official",
    warranty: "3 Years Official",
    specs: ["34\" 3440x1440 UWQHD 21:9 Ultra-Wide", "1500R Immersion Curve Factor", "144Hz Refresh Rate with 1ms Response", "Mystic Light RGB Backlight Atmosphere"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "viewsonic-vx2479",
    name: "ViewSonic VX2479-HD-PRO 24\" 165Hz 1ms IPS Esports Monitor",
    brand: "Dell",
    category: "monitors",
    price: 16500,
    was: 18500,
    img: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviews: 420,
    tag: "Bestseller",
    warranty: "3 Years Official",
    specs: ["24\" Fast IPS 1080p Esports Display", "165Hz Smooth Refresh Rate", "1ms MPRT Response with FreeSync", "Borderless Ultra-Slim Bezel Design"],
    inStock: true,
    emiAvailable: false,
  },

  /* ─────────────────────────── KEYBOARDS (12 ITEMS) ─────────────────────────── */
  {
    slug: "mech-rgb-keyboard-tkl",
    name: "Pro Mechanical RGB Wireless TKL Keyboard (Linear Red)",
    brand: "Logitech",
    category: "keyboards",
    price: 9990,
    was: 12990,
    img: keyboardImg,
    rating: 4.6,
    reviews: 512,
    tag: "Flash Deal",
    warranty: "2 Years Official",
    specs: ["LIGHTSPEED Pro-Grade Wireless", "Low Profile GL Linear Switches", "40h RGB Battery Endurance", "Aircraft-Grade 5052 Aluminum"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "logitech-mx-master-3s",
    name: "MX Master 3S Performance Wireless Ergonomic Mouse & Key Bundle",
    brand: "Logitech",
    category: "keyboards",
    price: 15490,
    was: 17900,
    img: keyboardImg,
    rating: 4.9,
    reviews: 480,
    tag: "Bestseller",
    warranty: "2 Years Official",
    specs: ["8K DPI Any-Surface Tracking", "Quiet Click 90% Less Noise", "MagSpeed Electromagnetic Scroll", "Multi-OS Flow Cross-Computer"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "keychron-q1-pro",
    name: "Keychron Q1 Pro Wireless Custom Mechanical Keyboard (Gateron Red)",
    brand: "Keychron",
    category: "keyboards",
    price: 22900,
    was: 25500,
    img: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 130,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["Full CNC Machined Aluminum Body", "QMK/VIA Programmable Customization", "Double-Gasket Acoustic Mount Design", "Hot-Swappable PCB with South-Facing RGB"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "keychron-k2-v2",
    name: "Keychron K2 V2 Wireless Bluetooth/USB Mechanical Keyboard",
    brand: "Keychron",
    category: "keyboards",
    price: 8900,
    was: 9900,
    img: "https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 390,
    tag: "Bestseller",
    warranty: "1 Year Official",
    specs: ["75% Compact 84-Key Layout", "Mac & Windows Keycaps Included", "4000mAh Massive Battery Capacity", "Hot-Swappable Gateron G Pro Switches"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "razer-blackwidow-v4-pro",
    name: "Razer BlackWidow V4 Pro Mechanical Gaming Keyboard (Green/Yellow)",
    brand: "Razer",
    category: "keyboards",
    price: 26500,
    was: 29900,
    img: "https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 85,
    tag: "Official",
    warranty: "2 Years Official",
    specs: ["Razer Command Dial & 8 Dedicated Macros", "True 8000Hz Polling Rate Performance", "3-Side Underglow & Per-Key RGB", "Plush Leatherette Magnetic Wrist Rest"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "logitech-g915-tkl",
    name: "Logitech G915 TKL Tenkeyless LIGHTSPEED Wireless RGB Mechanical",
    brand: "Logitech",
    category: "keyboards",
    price: 24500,
    was: 27500,
    img: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 215,
    tag: "Official",
    warranty: "2 Years Official",
    specs: ["Ultra-Thin 22mm Profile Architecture", "GL Tactile Low Profile Switches", "LIGHTSPEED 1ms + Bluetooth Dual Mode", "Dedicated Media Controls & Volume Roller"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "corsair-k70-rgb-pro",
    name: "Corsair K70 RGB PRO Mechanical Gaming Keyboard (Cherry MX Red)",
    brand: "Logitech",
    category: "keyboards",
    price: 16800,
    was: 18900,
    img: "https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 170,
    tag: "Official",
    warranty: "2 Years Official",
    specs: ["AXON Hyper-Processing 8,000Hz Polling", "Genuine German Cherry MX Switches", "Durable Double-Shot PBT Keycaps", "Tournament Switch for Competition Mode"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "asus-rog-azoth",
    name: "ASUS ROG Azoth 75% Custom Wireless Mechanical Gaming Keyboard",
    brand: "ASUS",
    category: "keyboards",
    price: 28500,
    was: 32000,
    img: "https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 65,
    tag: "New",
    warranty: "2 Years Official",
    specs: ["OLED Display & 3-Way Control Knob", "Silicone Gasket & 3-Layer Dampening", "Pre-Lubed ROG NX Mechanical Switches", "DIY Switch Lube Kit Included"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "royal-kludge-rk84",
    name: "Royal Kludge RK84 Tri-Mode Wireless RGB Mechanical Keyboard",
    brand: "Keychron",
    category: "keyboards",
    price: 4800,
    was: 5500,
    img: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviews: 650,
    tag: "Bestseller",
    warranty: "1 Year Official",
    specs: ["Bluetooth 5.0 + 2.4Ghz + Type-C Wired", "Hot-Swappable 3/5-Pin Switch PCB", "3750mAh Battery with Pass-Through USB", "Detachable Frame for Floating Key Look"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "redragon-k552-kumara",
    name: "Redragon K552 KUMARA RGB Mechanical Gaming Keyboard (Outemu Blue)",
    brand: "Logitech",
    category: "keyboards",
    price: 3200,
    was: 3800,
    img: "https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=800&q=80",
    rating: 4.6,
    reviews: 820,
    tag: "Bestseller",
    warranty: "1 Year Official",
    specs: ["Solid Metal & ABS Construction", "Clicky Tactile Mechanical Switches", "18 Backlit Rainbow RGB Lighting Modes", "Gold-Plated USB High-Speed Cable"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "akko-5075b-plus",
    name: "Akko 5075B Plus Multi-Mode Gasket Mount Mechanical Keyboard",
    brand: "Keychron",
    category: "keyboards",
    price: 7800,
    was: 8900,
    img: "https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 195,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["Gasket Mount with Polycarbonate Plate", "Multi-Mode (BT5.0, 2.4G, Type-C)", "Side Acrylic RGB Light Strips", "Akko CS Piano / Wine White Switches"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "razer-huntsman-mini",
    name: "Razer Huntsman Mini 60% Optical Gaming Keyboard (Linear Red)",
    brand: "Razer",
    category: "keyboards",
    price: 11900,
    was: 13500,
    img: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviews: 210,
    tag: "Official",
    warranty: "2 Years Official",
    specs: ["Razer Linear Optical Switches (Light-Speed Actuation)", "Doubleshot PBT Keycaps with Side Prints", "Onboard Memory & Chroma RGB Presets", "Detachable Type-C Braided Cable"],
    inStock: true,
    emiAvailable: false,
  },

  /* ─────────────────────────── TABLETS (12 ITEMS) ─────────────────────────── */
  {
    slug: "ipad-pro-m4-13",
    name: "iPad Pro 13\" Ultra Retina XDR Tandem OLED (M4 Chip / 256GB)",
    brand: "Apple",
    category: "tablets",
    price: 169900,
    was: 179900,
    img: tabletImg,
    rating: 4.9,
    reviews: 114,
    tag: "New",
    warranty: "1 Year Official",
    specs: ["Tandem OLED 1000 nits Full Screen", "Apple M4 10-core GPU Silicon", "5.1mm Ultra Thin Precision Design", "Apple Pencil Pro Support"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "slate-tab-pro-11",
    name: "Slate Tab S9 11\" Dynamic AMOLED 2X (128GB Wi-Fi + 5G)",
    brand: "Samsung",
    category: "tablets",
    price: 54900,
    was: 59900,
    img: tabletImg,
    rating: 4.8,
    reviews: 143,
    tag: "Bestseller",
    warranty: "1 Year Official",
    specs: ["120Hz Dynamic AMOLED 2X Display", "Snapdragon 8 Gen 2 for Galaxy", "IP68 Water & Dust Proof with S-Pen", "Quad AKG Dolby Atmos Speakers"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "apple-ipad-air-11-m2",
    name: "Apple iPad Air 11\" Liquid Retina (M2 Chip / 128GB Wi-Fi)",
    brand: "Apple",
    category: "tablets",
    price: 79900,
    was: 85000,
    img: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 210,
    tag: "New",
    warranty: "1 Year Official",
    specs: ["Supercharged by Apple M2 Chip", "11\" Liquid Retina True Tone Display", "Landscape 12MP Ultra Wide Front Camera", "Works with Magic Keyboard & Pencil Pro"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "apple-ipad-10th-gen",
    name: "Apple iPad 10th Generation 10.9\" 64GB Wi-Fi (A14 Bionic)",
    brand: "Apple",
    category: "tablets",
    price: 46500,
    was: 51000,
    img: "https://images.unsplash.com/photo-1561154464-82e9adf32764?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 490,
    tag: "Bestseller",
    warranty: "1 Year Official",
    specs: ["10.9\" Liquid Retina All-Screen Design", "A14 Bionic Chip 6-Core CPU", "Landscape 12MP Ultra Wide Camera with Center Stage", "Touch ID in Top Button & USB-C"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "samsung-galaxy-tab-s9-ultra",
    name: "Samsung Galaxy Tab S9 Ultra 14.6\" Dynamic AMOLED 256GB S-Pen",
    brand: "Samsung",
    category: "tablets",
    price: 128000,
    was: 139000,
    img: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 78,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["Giant 14.6\" 120Hz AMOLED Workstation", "Armor Aluminum Frame with IP68", "Snapdragon 8 Gen 2 for Galaxy", "Samsung DeX Desktop Multi-Window Mode"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "xiaomi-pad-6",
    name: "Xiaomi Pad 6 11\" 144Hz WQHD+ (8GB/256GB / Snapdragon 870)",
    brand: "Xiaomi",
    category: "tablets",
    price: 34900,
    was: 38500,
    img: "https://images.unsplash.com/photo-1561154464-82e9adf32764?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 360,
    tag: "Bestseller",
    warranty: "1 Year Official",
    specs: ["11\" WQHD+ 144Hz 7-Stage Variable Refresh", "Snapdragon 870 7nm Flagship Processor", "8840mAh Battery with 33W Fast Charge", "Quad Speakers with Dolby Atmos"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "samsung-galaxy-tab-s9-fe",
    name: "Samsung Galaxy Tab S9 FE 10.9\" 90Hz Display IP68 with S-Pen",
    brand: "Samsung",
    category: "tablets",
    price: 48500,
    was: 53000,
    img: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviews: 185,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["Included Water-Resistant S-Pen", "Vision Booster for Outdoor Clarity", "8000mAh Battery with 45W Fast Charging", "Exynos 1380 Smooth Octa-Core Chip"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "apple-ipad-mini-6",
    name: "Apple iPad mini 6th Gen 8.3\" Liquid Retina 64GB Wi-Fi",
    brand: "Apple",
    category: "tablets",
    price: 58000,
    was: 62500,
    img: "https://images.unsplash.com/photo-1561154464-82e9adf32764?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 220,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["Compact 8.3\" Pocketable Tablet Canvas", "A15 Bionic Chip with Neural Engine", "Apple Pencil 2 Magnetic Charging", "Ultra Wide Front Camera with Center Stage"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "oneplus-pad-2",
    name: "OnePlus Pad 2 12.1\" 3K 144Hz Display (Snapdragon 8 Gen 3)",
    brand: "OnePlus",
    category: "tablets",
    price: 62000,
    was: 68000,
    img: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 65,
    tag: "New",
    warranty: "1 Year Official",
    specs: ["12.1\" 3K 7:5 ReadFit Display", "Snapdragon 8 Gen 3 Flagship Architecture", "6-Speaker Audio System with Spatial Audio", "9510mAh Battery with 67W SUPERVOOC"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "xiaomi-redmi-pad-se",
    name: "Xiaomi Redmi Pad SE 11\" 90Hz FHD+ (8GB/256GB / Snapdragon 680)",
    brand: "Xiaomi",
    category: "tablets",
    price: 18500,
    was: 21000,
    img: "https://images.unsplash.com/photo-1561154464-82e9adf32764?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviews: 430,
    tag: "Bestseller",
    warranty: "1 Year Official",
    specs: ["11\" Eye Care 90Hz Smooth Display", "Quad Stereo Speakers Dolby Atmos", "8000mAh Battery All-Day Endurance", "Aluminum Alloy Unibody Construction"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "samsung-galaxy-tab-a9-plus",
    name: "Samsung Galaxy Tab A9+ 11\" 90Hz 64GB Wi-Fi (Snapdragon 695)",
    brand: "Samsung",
    category: "tablets",
    price: 24500,
    was: 27500,
    img: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviews: 280,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["11\" Bright 90Hz WUXGA Screen", "Quad Speakers 3D Surround Sound", "Split Screen 3-App Multitasking", "7040mAh Long Battery Performance"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "lenovo-tab-p12-pro",
    name: "Lenovo Tab P12 Pro 12.6\" 2K AMOLED 120Hz Precision Pen 3",
    brand: "Lenovo",
    category: "tablets",
    price: 68000,
    was: 74000,
    img: "https://images.unsplash.com/photo-1561154464-82e9adf32764?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 90,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["12.6\" 2K AMOLED HDR10+ Dolby Vision", "Snapdragon 870 Octa-Core Processor", "JBL Quad Speakers with Dolby Atmos", "10200mAh Battery with 30W Quick Charge"],
    inStock: true,
    emiAvailable: true,
  },

  /* ─────────────────────────── SPEAKERS (12 ITEMS) ─────────────────────────── */
  {
    slug: "boom-portable-speaker",
    name: "Boom XG-500 Rugged Waterproof Bluetooth Speaker",
    brand: "Sony",
    category: "speakers",
    price: 7990,
    was: 9990,
    img: speakerImg,
    rating: 4.6,
    reviews: 264,
    tag: "Flash Deal",
    warranty: "1 Year Official",
    specs: ["X-Balanced Speaker Drivers", "30h Mega Battery Playback", "IP66 Water & Dust Resistant", "Ambient RGB Lighting"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "jbl-boombox-3-wi-fi",
    name: "MegaBass 3 WiFi & Bluetooth 180W Portable Party Monster",
    brand: "JBL",
    category: "speakers",
    price: 46900,
    was: 52000,
    img: speakerImg,
    rating: 4.8,
    reviews: 168,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["180W RMS Massive Output", "Dolby Atmos 3D Sound", "24h Battery + Powerbank Output", "IP67 Dust & Water Proof"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "jbl-charge-5",
    name: "JBL Charge 5 Waterproof Portable Speaker with Powerbank",
    brand: "JBL",
    category: "speakers",
    price: 17500,
    was: 19500,
    img: "https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 540,
    tag: "Bestseller",
    warranty: "1 Year Official",
    specs: ["JBL Original Pro Sound with Dual Bass", "20 Hours of Playtime Endurance", "Built-In Powerbank Phone Charging", "IP67 Waterproof and Dustproof"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "jbl-flip-6",
    name: "JBL Flip 6 Eco-Friendly Portable 2-Way Speaker System",
    brand: "JBL",
    category: "speakers",
    price: 12800,
    was: 14200,
    img: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 620,
    tag: "Bestseller",
    warranty: "1 Year Official",
    specs: ["Separate Tweeter & Dual Radiators", "IP67 Waterproof & Dustproof Rugged", "12 Hours Battery Playtime", "PartyBoost Multiple Pairing"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "marshall-stanmore-iii",
    name: "Marshall Stanmore III Home Bluetooth Speaker Black",
    brand: "Marshall",
    category: "speakers",
    price: 42500,
    was: 46000,
    img: "https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 140,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["Re-Engineered Wider Soundstage", "Dynamic Loudness Tonal Balance", "Bluetooth 5.2 Next-Gen Ready", "Iconic Vintage Brass Dial Detailing"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "marshall-emberton-ii",
    name: "Marshall Emberton II Compact Waterproof Portable Speaker",
    brand: "Marshall",
    category: "speakers",
    price: 18900,
    was: 21500,
    img: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 290,
    tag: "Bestseller",
    warranty: "1 Year Official",
    specs: ["True Stereophonic 360° Sound Experience", "30+ Hours Portable Playtime", "Tough & Resilient IP67 Build", "Stack Mode Multiple Speaker Link"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "harman-kardon-onyx-studio-8",
    name: "Harman Kardon Onyx Studio 8 Premium Bluetooth Speaker",
    brand: "JBL",
    category: "speakers",
    price: 23500,
    was: 26000,
    img: "https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 195,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["Self-Tuning Room Calibration Audio", "Anodized Aluminum Handle Stand", "Dual Sound Wireless Pairing", "8 Hours Rechargeable Battery"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "sony-srs-xb100",
    name: "Sony SRS-XB100 Compact Wireless Waterproof Bluetooth Speaker",
    brand: "Sony",
    category: "speakers",
    price: 5800,
    was: 6500,
    img: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviews: 380,
    tag: "Bestseller",
    warranty: "1 Year Official",
    specs: ["Sound Diffusion Processor Technology", "16 Hours Battery with Battery Indicator", "IP67 Waterproof and Dustproof", "Hands-Free Calling with Echo Cancelling"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "bose-soundlink-flex",
    name: "Bose SoundLink Flex Bluetooth Speaker Outdoor Waterproof",
    brand: "Bose",
    category: "speakers",
    price: 16900,
    was: 18900,
    img: "https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 240,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["PositionIQ Technology Detects Orientation", "IP67 Waterproof, Dustproof & Floats", "Custom Transducer for Deep Clearest Audio", "12 Hours of Playtime per Charge"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "jbl-partybox-110",
    name: "JBL PartyBox 110 Portable 160W High Power Party Speaker",
    brand: "JBL",
    category: "speakers",
    price: 42000,
    was: 46000,
    img: "https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 115,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["160W Powerful JBL Original Pro Sound", "Dynamic Light Show Synced to the Beat", "12 Hours Battery with Mic & Guitar Inputs", "IPX4 Splashproof Build Quality"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "anker-soundcore-motion-boom-plus",
    name: "Anker Soundcore Motion Boom Plus 80W Outdoor Waterproof",
    brand: "Anker",
    category: "speakers",
    price: 14500,
    was: 16500,
    img: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 210,
    tag: "Official",
    warranty: "18 Months Official",
    specs: ["80W Booming Sound with BassUp Tech", "Titanium Drivers for Crystal Highs", "20-Hour Playtime with PowerIQ Output", "IP67 Waterproof and Dustproof Buoyant"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "xiaomi-mi-portable-bluetooth",
    name: "Xiaomi Mi Portable Bluetooth Speaker 16W Dual Sound",
    brand: "Xiaomi",
    category: "speakers",
    price: 3200,
    was: 3750,
    img: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=800&q=80",
    rating: 4.6,
    reviews: 580,
    tag: "Bestseller",
    warranty: "6 Months Official",
    specs: ["16W High Quality Audio Output", "IPX7 Waterproof for Pool & Shower", "13 Hours Long Lasting Battery", "True Wireless Stereo Multi-Connect"],
    inStock: true,
    emiAvailable: false,
  },

  /* ─────────────────────────── DRONES (12 ITEMS) ─────────────────────────── */
  {
    slug: "sky-drone-4k",
    name: "Sky Drone 4K HDR Quadcopter Fly More Combo",
    brand: "Xiaomi",
    category: "drones",
    price: 62900,
    was: 69900,
    img: droneImg,
    rating: 4.7,
    reviews: 98,
    tag: "New",
    warranty: "1 Year Official",
    specs: ["4K/60fps HDR Video Capture", "38 Min Flight Duration", "10km Transmission Reach", "Omnidirectional Vision Sensors"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "dji-mini-4-pro",
    name: "Aero Pro 4K HDR Ultralight Mini Drone (<249g Regulation Free)",
    brand: "DJI",
    category: "drones",
    price: 94900,
    was: 105000,
    img: droneImg,
    rating: 4.9,
    reviews: 86,
    tag: "Bestseller",
    warranty: "1 Year Official",
    specs: ["True Vertical 4K/60fps HDR", "Omnidirectional Obstacle Avoidance", "20km FHD Video Transmission", "Sub-249g Weight Certification"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "dji-mini-4-pro-fly-more",
    name: "DJI Mini 4 Pro Fly More Combo Plus with DJI RC 2 Remote",
    brand: "DJI",
    category: "drones",
    price: 118000,
    was: 128000,
    img: "https://images.unsplash.com/photo-1507582020432-2a3bc4ff7ac8?auto=format&fit=crop&w=800&q=80",
    rating: 5.0,
    reviews: 145,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["Includes 3 Intelligent Flight Batteries", "DJI RC 2 with Built-In FHD Screen", "Night Mode & D-Log M 10-Bit Color", "ActiveTrack 360° Follow"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "dji-air-3-fly-more",
    name: "DJI Air 3 Fly More Combo (DJI RC 2) Dual Primary Cameras",
    brand: "DJI",
    category: "drones",
    price: 168000,
    was: 180000,
    img: "https://images.unsplash.com/photo-1527977966376-1c8408f9f108?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 62,
    tag: "New",
    warranty: "1 Year Official",
    specs: ["Dual 1/1.3\" CMOS Medium Tele & Wide", "Up to 46 Minutes Max Flight Time", "Omnidirectional Sensing with APAS 5.0", "O4 20km HD Video Transmission"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "dji-mavic-3-pro",
    name: "DJI Mavic 3 Pro Cine Premium Triple-Camera Flagship Drone",
    brand: "DJI",
    category: "drones",
    price: 340000,
    was: 365000,
    img: "https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&w=800&q=80",
    rating: 5.0,
    reviews: 28,
    tag: "Pre-order",
    warranty: "1 Year Official",
    specs: ["4/3 CMOS Hasselblad Optical Camera", "Apple ProRes 422 HQ Triple Camera Encoding", "43-Min Maximum Flight Endurance", "Built-In 1TB SSD Storage"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "dji-avata-2-fpv",
    name: "DJI Avata 2 Fly More Combo FPV Goggles 3 & RC Motion 3",
    brand: "DJI",
    category: "drones",
    price: 135000,
    was: 148000,
    img: "https://images.unsplash.com/photo-1507582020432-2a3bc4ff7ac8?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 55,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["Intuitive Motion Control Acrobatics", "4K/60fps 155° Super-Wide Angle FOV", "Integrated Propeller Guard Safety", "DJI Goggles 3 Micro-OLED Dual Screens"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "dji-neo-drone",
    name: "DJI Neo 4K Ultra-Lightweight Hand-Launch Vlog Drone (<135g)",
    brand: "DJI",
    category: "drones",
    price: 28500,
    was: 32000,
    img: "https://images.unsplash.com/photo-1527977966376-1c8408f9f108?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 190,
    tag: "New",
    warranty: "1 Year Official",
    specs: ["Ultra-Compact 135g Palm Launch & Land", "4K Ultra-Stabilized Video with RockSteady", "AI Subject Tracking & Follow Framing", "Full-Coverage Propeller Protectors"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "dji-mini-3-rc",
    name: "DJI Mini 3 Fly More Combo (DJI RC Screen Remote)",
    brand: "DJI",
    category: "drones",
    price: 76000,
    was: 82000,
    img: "https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 215,
    tag: "Bestseller",
    warranty: "1 Year Official",
    specs: ["4K HDR True Vertical Shooting for Reels", "38-Min Battery (Up to 51 Min with Plus)", "Level 5 Wind Resistance 38kph", "Sub-249g Lightweight Build"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "xiaomi-fimi-x8-pro",
    name: "Xiaomi FIMI X8 Pro 4K HDR 15km Range 3-Axis Gimbal Drone",
    brand: "Xiaomi",
    category: "drones",
    price: 72000,
    was: 78000,
    img: "https://images.unsplash.com/photo-1507582020432-2a3bc4ff7ac8?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviews: 80,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["1/1.3\" 48MP CMOS Sensor F1.7 Aperture", "15km RokLink 4.0 HD Video Transmission", "47-Min Super Endurance Battery", "Super Night Video Algorithm"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "autel-evo-lite-plus",
    name: "Autel Robotics EVO Lite+ 6K Camera Drone Moonlight Night Mode",
    brand: "DJI",
    category: "drones",
    price: 145000,
    was: 158000,
    img: "https://images.unsplash.com/photo-1527977966376-1c8408f9f108?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 35,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["1-Inch CMOS 6K 30fps Video Camera", "Adjustable F2.8-F11 Aperture", "Defog Mode & Ultra-Long 40 Min Flight", "12km Video Transmission Range"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "sjrc-f22s-4k-pro",
    name: "SJRC F22S Pro 4K EIS 3.5km Laser Obstacle Avoidance Drone",
    brand: "Xiaomi",
    category: "drones",
    price: 34500,
    was: 38500,
    img: "https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&w=800&q=80",
    rating: 4.6,
    reviews: 140,
    tag: "Bestseller",
    warranty: "6 Months Official",
    specs: ["4K Camera with 2-Axis EIS Gimbal", "3.5km Real-Time Digital Repeater", "Front Laser Obstacle Sensor", "35 Mins Long Flight Duration"],
    inStock: true,
    emiAvailable: true,
  },
  {
    slug: "hubsan-zino-mini-pro",
    name: "Hubsan Zino Mini Pro 4K 48MP 249g Front/Back Obstacle Sensing",
    brand: "Xiaomi",
    category: "drones",
    price: 48000,
    was: 54000,
    img: "https://images.unsplash.com/photo-1507582020432-2a3bc4ff7ac8?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviews: 65,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["1/1.3\" 48MP CMOS 4K 30fps Video", "3-Direction Obstacle Avoidance System", "40 Minutes Max Flight Time", "6km Syncleas 3.0 Transmission"],
    inStock: true,
    emiAvailable: true,
  },

  /* ─────────────────────────── POWER BANKS (12 ITEMS) ─────────────────────────── */
  {
    slug: "watt-20k-power-bank",
    name: "HyperCharge 20000mAh 65W PD Laptop Power Bank",
    brand: "Xiaomi",
    category: "power",
    price: 3490,
    was: 4290,
    img: powerbankImg,
    rating: 4.7,
    reviews: 902,
    tag: "Bestseller",
    warranty: "6 Months Official",
    specs: ["65W Two-Way Fast PD Charging", "Triple Port Output (2x Type-C, 1x USB-A)", "Digital Smart LED Power Display", "Airline Approved Capacity"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "anker-737-power-bank",
    name: "PowerCore 24000mAh 140W Multi-Device PD Power Bank",
    brand: "Anker",
    category: "power",
    price: 13500,
    was: 15500,
    img: powerbankImg,
    rating: 4.8,
    reviews: 320,
    tag: "Flash Deal",
    warranty: "18 Months Official",
    specs: ["140W Ultra-Fast PD 3.1 Power Delivery", "Color Smart Digital Screen Display", "GaNPrime Energy-Saving Tech", "Recharges Powerbank in 52 Mins"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "baseus-blade-100w",
    name: "Baseus Blade 100W 20000mAh Ultra-Thin Laptop Power Bank",
    brand: "Baseus",
    category: "power",
    price: 7800,
    was: 8900,
    img: "https://images.unsplash.com/photo-1609081219090-a6d81d3085bf?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 280,
    tag: "Bestseller",
    warranty: "1 Year Official",
    specs: ["Ultra-Slim 18mm Flat Profile Design", "Dual 100W Type-C Laptop Charging", "Smart Status Display Time/Watts", "Supports MacBook, Dell, ThinkPad"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "ugreen-145w-power-bank",
    name: "Ugreen 145W 25000mAh 3-Port Laptop Power Bank PD 3.0",
    brand: "Ugreen",
    category: "power",
    price: 9800,
    was: 11200,
    img: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 195,
    tag: "Official",
    warranty: "18 Months Official",
    specs: ["145W Total Fast Charging Output", "25000mAh Recharges MacBook Air 1.3x", "Smart Digital Battery Percentage", "Flight Approved Carry-On Safe"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "baseus-adaman-65w",
    name: "Baseus Adaman 65W 20000mAh Metal Fast Charging Power Bank",
    brand: "Baseus",
    category: "power",
    price: 4200,
    was: 4800,
    img: "https://images.unsplash.com/photo-1609081219090-a6d81d3085bf?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviews: 510,
    tag: "Bestseller",
    warranty: "1 Year Official",
    specs: ["65W Fast PD for Laptops & Flagships", "All-Metal Premium Shell Finish", "LED Screen Voltage & Current Meter", "4 Outputs & 2 Inputs Connectivity"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "anker-533-powercore-30w",
    name: "Anker 533 PowerCore 10000mAh 30W Power Bank with Display",
    brand: "Anker",
    category: "power",
    price: 3800,
    was: 4500,
    img: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 340,
    tag: "Official",
    warranty: "18 Months Official",
    specs: ["30W High-Speed Output for iPhone/iPad", "Smart Digital Display with Health Info", "Compact Pocket-Sized Form Factor", "ActiveShield 2.0 Temperature Monitor"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "baseus-magsafe-wireless-10k",
    name: "Baseus Magnetic 10000mAh 20W MagSafe Wireless Power Bank",
    brand: "Baseus",
    category: "power",
    price: 3100,
    was: 3600,
    img: "https://images.unsplash.com/photo-1609081219090-a6d81d3085bf?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviews: 420,
    tag: "Bestseller",
    warranty: "1 Year Official",
    specs: ["Strong Magnetic Snap for iPhone 12-16", "15W Fast Wireless + 20W PD Wired", "Foldable Kickstand for Video Watching", "Anti-Slip Silicone Coating"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "xiaomi-50w-power-bank",
    name: "Xiaomi 50W 20000mAh Mi Power Bank Flash Charge Type-C",
    brand: "Xiaomi",
    category: "power",
    price: 3900,
    was: 4500,
    img: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviews: 290,
    tag: "Official",
    warranty: "6 Months Official",
    specs: ["50W Max Output Super Charge", "Charges Laptops via Type-C PD", "Low-Current Mode for Bands/Earbuds", "High-Quality Lithium-Ion Cells"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "ugreen-20000-30w",
    name: "Ugreen 20000mAh 30W Two-Way Fast Charging Power Bank",
    brand: "Ugreen",
    category: "power",
    price: 2850,
    was: 3400,
    img: "https://images.unsplash.com/photo-1609081219090-a6d81d3085bf?auto=format&fit=crop&w=800&q=80",
    rating: 4.6,
    reviews: 380,
    tag: "Official",
    warranty: "18 Months Official",
    specs: ["30W Max Two-Way Fast USB-C", "Charges iPhone 15 to 60% in 30 mins", "Simultaneous 3-Device Charging", "Comprehensive Multi-Protection IC"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "joyroom-30000mah-fast",
    name: "Joyroom JR-T015 30000mAh 22.5W Mega Capacity Power Bank",
    brand: "Baseus",
    category: "power",
    price: 2750,
    was: 3200,
    img: "https://images.unsplash.com/photo-1609081219090-a6d81d3085bf?auto=format&fit=crop&w=800&q=80",
    rating: 4.6,
    reviews: 490,
    tag: "Bestseller",
    warranty: "6 Months Official",
    specs: ["Massive 30000mAh (7+ Phone Charges)", "22.5W QC3.0 and PD Fast Charge", "LED Digital Precision Display", "Dual Input (Type-C + Micro USB)"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "remax-rpp-500-10k",
    name: "Remax RPP-500 10000mAh 22.5W Mini Fast Power Bank (Budget)",
    brand: "Xiaomi",
    category: "power",
    price: 1450,
    was: 1750,
    img: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&w=800&q=80",
    rating: 4.5,
    reviews: 670,
    tag: "Bestseller",
    warranty: "6 Months Official",
    specs: ["Pocket Mini Ultra-Lightweight Size", "22.5W Super Fast Flash Charging", "Dual Output (USB-A + Type-C)", "Flame-Retardant ABS Enclosure"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "cmf-65w-gan-power",
    name: "CMF Power 65W GaN High-Efficiency 3-Port Laptop Pack",
    brand: "Nothing",
    category: "power",
    price: 4600,
    was: 5200,
    img: "https://images.unsplash.com/photo-1609081219090-a6d81d3085bf?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 150,
    tag: "New",
    warranty: "1 Year Official",
    specs: ["Next-Gen GaN Fast Heat Dissipation", "65W USB PD 3.0 Protocol", "Charges Nothing Phone & Laptop Fast", "Compact Minimalist Design"],
    inStock: true,
    emiAvailable: false,
  },

  /* ─────────────────────────── ACCESSORIES (13 ITEMS) ─────────────────────────── */
  {
    slug: "apple-20w-usb-c-adapter",
    name: "Apple 20W USB-C Power Adapter (Original Box Pack)",
    brand: "Apple",
    category: "accessories",
    price: 2450,
    was: 2850,
    img: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 820,
    tag: "Bestseller",
    warranty: "1 Year Official",
    specs: ["Official Apple Fast Charging Standard", "Charges iPhone 15/16 to 50% in 30 mins", "Compact Foldable Pins for Travel", "Universal Type-C PD Protocol"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "apple-magsafe-charger",
    name: "Apple MagSafe Wireless Charger 15W Fast Charge (1m)",
    brand: "Apple",
    category: "accessories",
    price: 4800,
    was: 5400,
    img: "https://images.unsplash.com/photo-1622445262464-84b14e32452e?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 410,
    tag: "Official",
    warranty: "1 Year Official",
    specs: ["Perfect Magnetic Alignment for iPhones", "Up to 15W Faster Wireless Power", "Qi Compatible for AirPods / Android", "Braided High-Durability Cable"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "anker-prime-100w-gan",
    name: "Anker Prime 100W 3-Port GaN Wall Fast Charger (2C+1A)",
    brand: "Anker",
    category: "accessories",
    price: 7200,
    was: 8200,
    img: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 260,
    tag: "New",
    warranty: "18 Months Official",
    specs: ["100W Max Single Port Laptop Power", "43% Smaller than Apple 96W Charger", "ActiveShield 2.0 Safety Sensors", "Multi-Device Dynamic Power Sharing"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "anker-511-nano-3-30w",
    name: "Anker 511 Nano 3 30W GaN Ultra-Compact Fast Charger",
    brand: "Anker",
    category: "accessories",
    price: 2100,
    was: 2500,
    img: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 590,
    tag: "Bestseller",
    warranty: "18 Months Official",
    specs: ["30W Output Powers iPhone & MacBook Air", "70% Smaller than Original 30W Charger", "Foldable Plug Pins Design", "Bio-Based Eco Friendly Shell"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "baseus-gan5-pro-65w",
    name: "Baseus GaN5 Pro 65W Fast Charger (2x Type-C + 1x USB-A)",
    brand: "Baseus",
    category: "accessories",
    price: 2650,
    was: 3100,
    img: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 730,
    tag: "Bestseller",
    warranty: "1 Year Official",
    specs: ["65W BPS II Intelligent Power Allocation", "Upgraded GaN5 Chipset 10% Cooler", "Charges Laptop + Phone + Earbuds Together", "Complimentary 100W Fast Type-C Cable"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "baseus-100w-braided-cable",
    name: "Baseus Tungsten Gold 100W Fast Charging Type-C to Type-C Cable 2M",
    brand: "Baseus",
    category: "accessories",
    price: 750,
    was: 950,
    img: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 940,
    tag: "Bestseller",
    warranty: "6 Months Official",
    specs: ["100W 5A E-Marker High-Speed Chip", "High-Density Nylon Braided Jacket", "Tungsten Alloy Mirror Gloss Connectors", "480Mbps Data Transmission Speed"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "ugreen-nexode-140w-gan",
    name: "Ugreen Nexode 140W 3-Port GaN Fast Desktop Charger PD 3.1",
    brand: "Ugreen",
    category: "accessories",
    price: 9500,
    was: 10800,
    img: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 140,
    tag: "Official",
    warranty: "18 Months Official",
    specs: ["Single Port 140W for MacBook Pro 16\"", "Thermal Guard Real-Time Temp Control", "Power Delivery 3.1 Next-Gen Protocol", "Includes 240W Braided Type-C Cable"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "ugreen-9-in-1-usb-c-hub",
    name: "Ugreen 9-in-1 USB-C Multifunction Docking Hub (4K HDMI / 100W PD)",
    brand: "Ugreen",
    category: "accessories",
    price: 4200,
    was: 4800,
    img: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 310,
    tag: "Bestseller",
    warranty: "18 Months Official",
    specs: ["4K@60Hz HDMI Ultra-HD Output", "100W USB-C Power Pass-Through", "Gigabit RJ45 Ethernet Port 1000Mbps", "SD/TF Card Reader + 3x USB 3.0"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "ugreen-mfi-lightning-cable",
    name: "Ugreen USB-C to Lightning Cable Apple MFi Certified (1.5M)",
    brand: "Ugreen",
    category: "accessories",
    price: 1250,
    was: 1500,
    img: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 620,
    tag: "Official",
    warranty: "18 Months Official",
    specs: ["Apple Certified MFi C94 Connector", "3A Fast PD Charging Support", "Reinforced Strain Relief 15000+ Bends", "480Mbps Data Sync Transmission"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "spigen-ultra-hybrid-magsafe",
    name: "Spigen Ultra Hybrid MagFit Case for iPhone 16 Pro (Crystal Clear)",
    brand: "Spigen",
    category: "accessories",
    price: 2850,
    was: 3300,
    img: "https://images.unsplash.com/photo-1601593346740-925612772716?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviews: 380,
    tag: "Bestseller",
    warranty: "Official Brand Pack",
    specs: ["Built-In Strong Magnetic MagSafe Ring", "Air Cushion Shock Absorption Corners", "Anti-Yellowing Blue Resin Technology", "Raised Lips for Screen & Camera Guard"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "nillkin-camshield-pro-s24",
    name: "Nillkin CamShield Pro Armor Case for Galaxy S24 Ultra",
    brand: "Spigen",
    category: "accessories",
    price: 1650,
    was: 1950,
    img: "https://images.unsplash.com/photo-1601593346740-925612772716?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviews: 520,
    tag: "Official",
    warranty: "Official Brand Pack",
    specs: ["Slide Camera Cover Lens Privacy Guard", "TPU Bumpers + Hard PC Back Protection", "Anti-Slip Tactile Texture Grips", "Wireless Charging Compatible Without Removal"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "esr-halolock-car-charger",
    name: "ESR HaloLock MagSafe Wireless Car Charger Mount 15W CryoBoost",
    brand: "ESR",
    category: "accessories",
    price: 3400,
    was: 3950,
    img: "https://images.unsplash.com/photo-1622445262464-84b14e32452e?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 175,
    tag: "New",
    warranty: "1 Year Official",
    specs: ["CryoBoost Phone-Cooling Fan Technology", "Ultra-Strong 1400g Magnetic Holding Force", "Air Vent Secure Mounting Bracket", "360-Degree Ball Joint Rotation"],
    inStock: true,
    emiAvailable: false,
  },
  {
    slug: "belkin-ultraglass-screen-guard",
    name: "Belkin UltraGlass 2 Treated Screen Protector for iPhone",
    brand: "Apple",
    category: "accessories",
    price: 1850,
    was: 2200,
    img: "https://images.unsplash.com/photo-1601593346740-925612772716?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviews: 290,
    tag: "Official",
    warranty: "Official Brand Pack",
    specs: ["Double Ion-Exchange Strengthened Glass", "2.7x Stronger Than Standard Tempered Glass", "Anti-Microbial Coating Minimizes Bacteria", "Flawless Easy Align Tray Included"],
    inStock: true,
    emiAvailable: false,
  },
];
